package main

import (
	"bytes"
	"crypto/rand"
	"fmt"
	"go/format"
	"os"
)

type obfuscatedSecret struct {
	Data []byte
	Mask []byte
}

func main() {
	botID := os.Getenv("CHATBOTKIT_BOT_ID")
	if botID == "" {
		exitf("CHATBOTKIT_BOT_ID is required")
	}

	mintToken := os.Getenv("CHATBOTKIT_SESSION_MINT_TOKEN")
	if mintToken == "" {
		exitf("CHATBOTKIT_SESSION_MINT_TOKEN is required")
	}

	obfuscatedBotID, err := obfuscate(botID)
	if err != nil {
		exitf("failed to obfuscate bot ID: %v", err)
	}

	obfuscatedMintToken, err := obfuscate(mintToken)
	if err != nil {
		exitf("failed to obfuscate mint token: %v", err)
	}

	var src bytes.Buffer

	src.WriteString("package main\n\n")
	src.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")

	emitSecret(&src, "embeddedBotID", obfuscatedBotID)
	emitSecret(&src, "embeddedSessionMintToken", obfuscatedMintToken)

	formatted, err := format.Source(src.Bytes())
	if err != nil {
		formatted = src.Bytes()
	}

	if err := os.WriteFile("secrets_gen.go", formatted, 0o600); err != nil {
		exitf("failed to write secrets_gen.go: %v", err)
	}

	fmt.Println("generated secrets_gen.go")
}

func obfuscate(value string) (obfuscatedSecret, error) {
	plain := []byte(value)

	mask := make([]byte, len(plain))
	if _, err := rand.Read(mask); err != nil {
		return obfuscatedSecret{}, err
	}

	data := make([]byte, len(plain))
	for i := range plain {
		data[i] = plain[i] ^ mask[i]
	}

	return obfuscatedSecret{
		Data: data,
		Mask: mask,
	}, nil
}

func emitSecret(out *bytes.Buffer, name string, secret obfuscatedSecret) {
	fmt.Fprintf(out, "var %s = secretBytes{\n", name)
	fmt.Fprintf(out, "\tdata: []byte{%s},\n", byteList(secret.Data))
	fmt.Fprintf(out, "\tmask: []byte{%s},\n", byteList(secret.Mask))
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)
}

func byteList(values []byte) string {
	var out bytes.Buffer

	for i, value := range values {
		if i > 0 {
			out.WriteString(", ")
		}

		fmt.Fprintf(&out, "0x%02x", value)
	}

	return out.String()
}

func exitf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "error: "+format+"\n", args...)
	os.Exit(1)
}
